components:
- name: Store
  params:
    batch_size: 100
    dataset_info:
      path: Tevatron/wikipedia-nq-corpus
      split: train
    encoding_method: wikipedia_hf
  type: fastrag.data_loaders.HFDatasetLoader
- name: Retriever
  params:
    document_store: Store
    top_k: 10
    use_gpu: false
  type: ColBERTRetriever
- name: Reranker
  params:
    batch_size: 32
    model_name_or_path: cross-encoder/ms-marco-MiniLM-L-12-v2
    top_k: 10
    use_gpu: true
  type: SentenceTransformersRanker
pipelines:
- name: my_pipeline
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reranker
  - inputs:
    - Reranker
    name: Reader
version: 1.12.2
